'use strict';

module.exports = {
    extends: 'stylelint-config-standard-scss',
    plugins: ['stylelint-order'],
    rules: {
        'at-rule-empty-line-before': ['always', {
            except: [
                'blockless-after-same-name-blockless',
                'first-nested'
            ],
            ignore: [
                'after-comment',
                'inside-block',
                'blockless-after-same-name-blockless',
                'blockless-after-blockless'
            ]
        }],
        'at-rule-no-unknown': null,
        'color-named': 'never',
        'font-family-name-quotes': 'always-where-recommended',
        'function-url-quotes': 'always',
        'max-nesting-depth': 3,
        'no-unknown-animations': true,
        'order/properties-order': [
            'content',
            'speak',
            'display',

            'position',
            'top',
            'right',
            'bottom',
            'left',
            'z-index',

            'float',
            'clear',

            'box-sizing',

            'width',
            'min-width',
            'max-width',

            'height',
            'min-height',
            'max-height',

            'margin',
            'margin-top',
            'margin-right',
            'margin-bottom',
            'margin-left',

            'padding',
            'padding-top',
            'padding-right',
            'padding-bottom',
            'padding-left',

            'flex',
            'flex-align',
            'flex-basis',
            'flex-direction',
            'flex-wrap',
            'flex-flow',
            'flex-shrink',
            'flex-grow',
            'flex-order',
            'flex-pack',
            'align-content',
            'align-items',
            'align-self',
            'justify-content',
            'order',

            'overflow',
            'overflow-x',
            'overflow-y',
            '-webkit-overflow-scrolling',
            '-ms-overflow-style',

            'columns',
            'column-count',
            'column-fill',
            'column-gap',
            'column-rule',
            'column-rule-width',
            'column-rule-style',
            'column-rule-color',
            'column-span',
            'column-width',

            'orphans',
            'widows',
            'clip',
            'opacity',
            'visibility',

            'border',
            'border-color',
            'border-style',
            'border-width',
            'border-top',
            'border-top-color',
            'border-top-style',
            'border-top-width',
            'border-right',
            'border-right-color',
            'border-right-style',
            'border-right-width',
            'border-bottom',
            'border-bottom-color',
            'border-bottom-style',
            'border-bottom-width',
            'border-left',
            'border-left-color',
            'border-left-style',
            'border-left-width',
            'border-radius',
            'border-top-left-radius',
            'border-top-right-radius',
            'border-bottom-right-radius',
            'border-bottom-left-radius',
            'border-image',
            'border-image-source',
            'border-image-slice',
            'border-image-width',
            'border-image-outset',
            'border-image-repeat',
            'border-spacing',
            'border-collapse',

            'outline',
            'outline-width',
            'outline-style',
            'outline-color',
            'outline-offset',

            'background',
            'background-color',
            'background-image',
            'background-repeat',
            'background-attachment',
            'background-position',
            'background-position-x',
            'background-position-y',
            'background-clip',
            'background-origin',
            'background-size',

            'box-shadow',

            'color',
            'font',
            'font-family',
            'font-size',
            'font-style',
            'font-weight',
            'font-variant',
            'font-size-adjust',
            'font-stretch',
            'font-effect',
            'font-emphasize',
            'font-emphasize-position',
            'font-emphasize-style',
            'font-smooth',
            'hyphens',
            'text-align',
            'text-align-last',
            'text-emphasis',
            'text-emphasis-color',
            'text-emphasis-style',
            'text-emphasis-position',
            'text-decoration',
            'text-indent',
            'text-justify',
            'text-outline',
            'text-overflow',
            'text-overflow-ellipsis',
            'text-overflow-mode',
            'text-shadow',
            'text-transform',
            'text-wrap',
            'line-height',
            'letter-spacing',
            'word-break',
            'word-spacing',
            'word-wrap',
            'overflow-wrap',
            'tab-size',
            'white-space',
            'vertical-align',
            'direction',
            'unicode-bidi',

            'list-style',
            'list-style-position',
            'list-style-type',
            'list-style-image',

            'pointer-events',
            'touch-action',
            'cursor',

            'fill',
            'fill-opacity',
            'stroke',
            'stroke-opacity',
            'stroke-width',
            'shape-rendering',

            'table-layout',
            'empty-cells',
            'caption-side',

            'quotes',
            'counter-reset',
            'counter-increment',
            'resize',
            'user-select',
            'nav-index',
            'nav-up',
            'nav-right',
            'nav-down',
            'nav-left',

            'transform',
            'transform-origin',
            'perspective',
            'zoom',

            'transition',
            'transition-delay',
            'transition-timing-function',
            'transition-duration',
            'transition-property',

            'animation',
            'animation-name',
            'animation-duration',
            'animation-fill-mode',
            'animation-play-state',
            'animation-timing-function',
            'animation-delay',
            'animation-iteration-count',
            'animation-direction',

            'filter',
            'appearance',

            'page-break-after',
            'page-break-before',
            'page-break-inside'
        ],
        'selector-class-pattern': [/^(.)?([a-z0-9](-[a-z0-9])?)+(__([a-z0-9].?)+)?(--([a-z0-9].?)+)?$/, { resolveNestedSelectors: true }],
        'selector-id-pattern': null,
        'selector-max-id': 0,
        'value-keyword-case': 'lower',
        'value-no-vendor-prefix': true
    }
};
