module.exports = {
    rules: {
        'selector-class-pattern': [/^(.)?(\w(-\w)?)+(__(\w.?)+)?(--(\w.?)+)?$/, { resolveNestedSelectors: true }],
        'selector-combinator-space-after': 'always',
        'selector-combinator-space-before': 'always',
        'selector-id-pattern': null,
        'selector-max-empty-lines': 0,
        'selector-max-specificity': null,
        'selector-no-attribute': null,
        'selector-no-combinator': null,
        'selector-no-id': true,
        'selector-no-type': null,
        'selector-no-universal': null,
        'selector-no-vendor-prefix': null,
        'selector-root-no-composition': null,
        'selector-attribute-brackets-space-inside': 'never',
        'selector-attribute-operator-space-after': 'never',
        'selector-attribute-operator-space-before': 'never',
        'selector-list-comma-newline-after': 'always',
        'selector-list-comma-newline-before': 'never-multi-line',
        'selector-list-comma-space-after': 'always-single-line',
        'selector-list-comma-space-before': 'never',
        'selector-pseudo-class-case': 'lower',
        'selector-pseudo-class-no-unknown': true,
        'selector-pseudo-class-parentheses-space-inside': 'never',
        'selector-pseudo-element-case': 'lower',
        'selector-pseudo-element-colon-notation': 'double',
        'selector-pseudo-element-no-unknown': true,
        'selector-type-case': 'lower',
        'selector-type-no-unknown': true
    }
};
